### ISSUE TITLE
2020-1-MLT-005 takes too long to load

### ISSUE THREAD

**Issue by hettlage** [saltastroops/salt-api#155]
Requesting GET /proposals/2020-1-MLT-005 takes too long.

I also got errors with missing data once, but I could not reproduce this.

**Comment by Eb-Zeero** [comment]
P1ProposalTarget takes a long time to load, for proposals with more targets.
Example 2020-1-MLT-004 has 254 targets it will take about 45 seconds to load.

method name:
`def _get_phase_one_targets(self, proposal_code: str) -> List[Dict[str, Any]]`

**Comment by hettlage** [comment]
The issue is that the `Target_Id` column of the `MovingTable` table is not indexed.

**Comment by Eb-Zeero** [comment]
issue fixed
