### ISSUE TITLE
ProposalCode is not validating properly

### ISSUE THREAD

**Issue by hettlage** [saltastroops/salt-api#209]
The validation of the Pydantic model `ProposalCode` in `web/schema/common.py` relies on the schema being updated by the `__modify_schema__` method. But this method is never called.

**Comment by Eb-Zeero** [comment]
More comment:
 pydentic doesn't pick up when you pass an invalid proposal code. and it should raise 422 not 404.
 frontend tests expect 404 to be fixed as well
