### ISSUE TITLE
Block visit status update must also update rejection reason

### ISSUE THREAD

**Issue by hettlage** [saltastroops/salt-api#34]
The (repository) function for updating the block visit status currently does not update the rejection reason.

**Comment by hettlage** [comment]
It might be best to just have a PATCH method for updating the block visit.

This would also make the GET method for requesting the block visit status obsolete.

**Comment by mofokeng-chaka** [comment]
This issue is handled by the linked and merged PR. It didn't close automatically, so I am closing it.
