### ISSUE TITLE
General method for RSS masks in magazine

### ISSUE THREAD

**Issue by hettlage** [saltastroops/salt-api#43]
There currently is a method `get_mos_mask_in_magazine` in `instrument_repository.py` and `rss_repository.py`. These should be replaced with more general methods return _all_ RSS masks in the magazine. Such methods should accept an array of mask types to filter by.

**Comment by hettlage** [comment]
This implies replacing the corresponding API endpoint.

**Comment by hettlage** [comment]
And the methods / API endpoint should include the mask type and description (cf. https://astronomers.salt.ac.za/status/).

**Comment by mofokeng-chaka** [comment]
This issue is already handled by the linked and merged PR. I am closing it.
